# Generated by Django 4.1 on 2022-08-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.CharField(max_length=400)),
                ('isbn', models.IntegerField()),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.authors')),
                ('shelfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.shelves')),
            ],
        ),
    ]
